export const AUDIO_CODES = {
  GET_AUDIO_GUIDES_SUCCESS: "AUDIO_GUIDE_LIST_SUCCESS",
  GET_AUDIO_GUIDES_BY_CATEGORY_SUCCESS: "AUDIO_GUIDE_CATEGORY_LIST_SUCCESS",
  TOGGLE_AUDIO_LIKE_SUCCESS: "AUDIO_GUIDE_LIKE_TOGGLE_SUCCESS",
  SAVE_AUDIO_GUIDE_SUCCESS: "AUDIO_GUIDE_SAVE_SUCCESS",
  AUDIO_GUIDE_NOT_FOUND: "AUDIO_GUIDE_NOT_FOUND_404",
  BAD_REQUEST: "BAD_REQUEST_400",
  AUDIO_SAVE_FAILED: "AUDIO_SAVE_FAILED_500",
} as const;

export const AUDIO_MESSAGES = {
  GET_AUDIO_GUIDES_SUCCESS: "청각 오디오 가이드 목록 조회에 성공했습니다.",
  GET_AUDIO_GUIDES_BY_CATEGORY_SUCCESS:
    "카테고리별 청각 오디오 가이드 목록 조회에 성공했습니다.",
  TOGGLE_AUDIO_LIKE_SUCCESS: "청각 오디오 가이드 좋아요 처리에 성공했습니다.",
  SAVE_AUDIO_GUIDE_SUCCESS: "청각 오디오 가이드 저장에 성공했습니다.",
  AUDIO_GUIDE_NOT_FOUND: "해당 청각 오디오 가이드를 찾을 수 없습니다.",
  BAD_REQUEST: "잘못된 요청 파라미터 형식입니다.",
  AUDIO_SAVE_FAILED: "청각 오디오 가이드 저장을 실패하였습니다.",
} as const;
 