export const AUDIO_CODES = {
  GET_AUDIO_GUIDES_SUCCESS: "AUDIO_GUIDE_LIST_SUCCESS",
  GET_AUDIO_GUIDES_BY_CATEGORY_SUCCESS: "AUDIO_GUIDE_CATEGORY_LIST_SUCCESS",
  GET_LIKED_AUDIO_GUIDES_SUCCESS: "AUDIO_GUIDE_LIKED_LIST_SUCCESS",
  TOGGLE_AUDIO_LIKE_SUCCESS: "AUDIO_GUIDE_LIKE_TOGGLE_SUCCESS",
  AUDIO_GUIDE_NOT_FOUND: "AUDIO_GUIDE_NOT_FOUND_404",
  BAD_REQUEST: "AUDIO_GUIDE_INVALID_ID_400",
  INVALID_PAGINATION: "AUDIO_GUIDE_INVALID_PAGINATION_400",
  INVALID_CATEGORY: "AUDIO_GUIDE_INVALID_CATEGORY_400",
  AUDIO_LIST_FAILED: "AUDIO_GUIDE_LIST_FAILED_500",
  LIKED_AUDIO_LIST_FAILED: "AUDIO_GUIDE_LIKED_LIST_FAILED_500",
  AUDIO_LIKE_FAILED: "AUDIO_GUIDE_LIKE_TOGGLE_FAILED_500",
} as const;

export const AUDIO_MESSAGES = {
  GET_AUDIO_GUIDES_SUCCESS: "청각 오디오 가이드 목록 조회에 성공했습니다.",
  GET_AUDIO_GUIDES_BY_CATEGORY_SUCCESS:
    "카테고리별 청각 오디오 가이드 목록 조회에 성공했습니다.",
  GET_LIKED_AUDIO_GUIDES_SUCCESS:
    "좋아요한 청각 오디오 가이드 목록 조회에 성공했습니다.",
  TOGGLE_AUDIO_LIKE_SUCCESS: "청각 오디오 가이드 좋아요 처리에 성공했습니다.",
  AUDIO_GUIDE_NOT_FOUND: "해당 청각 오디오 가이드를 찾을 수 없습니다.",
  BAD_REQUEST: "유효하지 않은 오디오 ID입니다.",
  INVALID_PAGINATION: "cursor 또는 size가 유효하지 않습니다.",
  INVALID_CATEGORY: "유효하지 않은 오디오 카테고리입니다.",
  AUDIO_LIST_FAILED: "청각 오디오 가이드 목록 조회에 실패했습니다.",
  LIKED_AUDIO_LIST_FAILED:
    "좋아요한 청각 오디오 가이드 목록 조회에 실패했습니다.",
  AUDIO_LIKE_FAILED: "청각 오디오 가이드 좋아요 처리에 실패했습니다.",
} as const;
