export const AUTH_CODES = {
  LOCAL_SIGNUP_SUCCESS: "AUTH_LOCAL_SIGNUP_SUCCESS",
  SIGNUP_INVALID_REQUEST: "AUTH_SIGNUP_INVALID_REQUEST_400",
  EMAIL_DUPLICATE: "AUTH_EMAIL_DUPLICATE_409",
  LINK_ACCOUNT_REQUIRED: "AUTH_LINK_ACCOUNT_REQUIRED_409",
  SIGNUP_FAILED: "AUTH_SIGNUP_FAILED_500",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED_401",
  REFRESH_SUCCESS: "AUTH_REFRESH_SUCCESS",
  REFRESH_INVALID: "AUTH_REFRESH_INVALID_401",
  ME_SUCCESS: "AUTH_ME_SUCCESS",
  ME_NOT_FOUND: "AUTH_ME_NOT_FOUND_404",
} as const;

export const AUTH_MESSAGES = {
  LOCAL_SIGNUP_SUCCESS: "회원가입에 성공했습니다.",
  SIGNUP_INVALID_REQUEST: "입력값이 올바르지 않습니다.",
  EMAIL_DUPLICATE: "이미 가입된 이메일입니다.",
  LINK_ACCOUNT_REQUIRED:
    "동일한 이메일의 카카오 계정이 있습니다. 계정을 연동하시겠어요?",
  SIGNUP_FAILED: "회원가입 처리 중 오류가 발생했습니다.",
  LOGIN_SUCCESS: "로그인에 성공했습니다.",
  LOGIN_FAILED: "이메일 또는 비밀번호가 올바르지 않습니다.",
  REFRESH_SUCCESS: "토큰 갱신에 성공했습니다.",
  REFRESH_INVALID: "유효하지 않은 refresh token입니다.",
  ME_SUCCESS: "사용자 정보 조회에 성공했습니다.",
  ME_NOT_FOUND: "사용자를 찾을 수 없습니다.",
} as const;
