export const PAUZE_USAGE_CODES = {
  RECORD_SUCCESS: "COMMON_200",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED_401",
  SAVE_FAILED: "AGGREGATION_SAVE_FAILED_500",
  STATISTICS_GET_FAILED: "AGGREGATION_GET_FAILED_500",
} as const;

export const PAUZE_USAGE_MESSAGES = {
  RECORD_SUCCESS: "요청에 성공했습니다.",
  AUTH_UNAUTHORIZED: "인증이 필요합니다.",
  SAVE_FAILED: "누적 집계를 실패하였습니다.",
  STATISTICS_GET_FAILED: "사용 통계 조회를 실패하였습니다.",
} as const;
