export const PAUZE_USAGE_CODES = {
  RECORD_SUCCESS: "PAUZE_USAGE_RECORD_SUCCESS",
  STATISTICS_GET_SUCCESS: "PAUZE_USAGE_STATISTICS_GET_SUCCESS",
  INVALID_COMPLETION_ID: "PAUZE_USAGE_INVALID_COMPLETION_ID_400",
  SAVE_FAILED: "PAUZE_USAGE_SAVE_FAILED_500",
  STATISTICS_GET_FAILED: "PAUZE_USAGE_STATISTICS_GET_FAILED_500",
} as const;

export const PAUZE_USAGE_MESSAGES = {
  RECORD_SUCCESS: "요청에 성공했습니다.",
  STATISTICS_GET_SUCCESS: "사용 통계 조회에 성공했습니다.",
  INVALID_COMPLETION_ID: "completionId는 UUID 형식이어야 합니다.",
  SAVE_FAILED: "누적 집계를 실패하였습니다.",
  STATISTICS_GET_FAILED: "사용 통계 조회를 실패하였습니다.",
} as const;
