export const USER_CODES = {
  ME_SUCCESS: "USER_ME_SUCCESS",
  PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  PROFILE_UPDATE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
  SETTINGS_UPDATE_SUCCESS: "USER_SETTINGS_UPDATE_SUCCESS",
  WITHDRAW_SUCCESS: "USER_WITHDRAW_SUCCESS",
  NOT_FOUND: "USER_NOT_FOUND_404",
  PROFILE_INVALID: "USER_PROFILE_INVALID_400",
  NICKNAME_DUPLICATE: "USER_NICKNAME_DUPLICATE_409",
  SETTINGS_INVALID: "USER_SETTINGS_INVALID_400",
  WITHDRAW_INVALID: "USER_WITHDRAW_INVALID_400",
  PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED_500",
  UNAUTHORIZED: "AUTH_UNAUTHORIZED_401",
} as const;

export const USER_MESSAGES = {
  ME_SUCCESS: "마이페이지 조회에 성공했습니다.",
  PROFILE_SUCCESS: "프로필 조회에 성공했습니다.",
  PROFILE_UPDATE_SUCCESS: "저장되었습니다.",
  SETTINGS_UPDATE_SUCCESS: "설정을 수정했습니다.",
  WITHDRAW_SUCCESS: "회원 탈퇴가 완료되었습니다.",
  NOT_FOUND: "사용자를 찾을 수 없습니다.",
  PROFILE_INVALID: "입력값이 올바르지 않습니다.",
  NICKNAME_DUPLICATE: "이미 사용 중인 닉네임입니다.",
  SETTINGS_INVALID: "입력값이 올바르지 않습니다.",
  WITHDRAW_INVALID: "탈퇴 확인이 필요합니다.",
  PROFILE_UPDATE_FAILED: "저장에 실패했습니다. 다시 시도해주세요.",
  UNAUTHORIZED: "인증이 필요합니다.",
} as const;
